behaviors:
  Spy:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.1
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 30000
    threaded: true
    
environment_parameters:
    spy_curriculum:
        curriculum:
            - name: lesson_1
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 1.0
            - name: lesson_2
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 2.0
            - name: lesson_3
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 3.0
            - name: lesson_4
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 4.0
            - name: lesson_5
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 5.0
            - name: lesson_6
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 6.0
            - name: lesson_7
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 7.0
            - name: lesson_8
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 8.0
            - name: lesson_9
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 9.0
            - name: lesson_10
              completion_criteria:
                  measure: reward
                  behavior: Spy
                  signal_smoothing: true
                  min_lesson_length: 100
                  threshold: 0.9
              value: 10.0
            
            
    